"""isbn field added to Book

Revision ID: 10e207f38a48
Revises: db5f3d5292d9
Create Date: 2025-03-20 03:04:30.853505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e207f38a48'
down_revision = 'db5f3d5292d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
