"""added isbn unique constraint

Revision ID: bf47f73fc8f4
Revises: 10e207f38a48
Create Date: 2025-03-20 11:13:00.075130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf47f73fc8f4'
down_revision = '10e207f38a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_isbn', ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint('uq_isbn', type_='unique')

    # ### end Alembic commands ###
